name: Deploy grigory-laptop

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: "${DOCKER_USERNAME}/test:${IMAGE_TAG}"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 'Deploy'
        run: |
          docker compose run -d --force-recreate ${DOCKER_USERNAME}/test:${IMAGE_TAG}
